<?php
$this->headTitle($title);

 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('signup'));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formRow($form->get('username'));
 echo $this->formRow($form->get('password'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 
/*$form = $this->form;
$form->prepare();
$form->setAttribute('action', '/signup');
$form->get('username')->setAttribute('class', 'textbox');
$form->get('password')->setAttribute('class', 'textbox');
$form->get('submit')->setAttribute('class', 'button');*/
?>
           
